# SERVICE DISCOVERY
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka

# CENTRALIZED CONFIGURATION
# Enable Actuator Refresh Endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"

# REST CONTROLLERS
# Pretty-print JSON for non-HATEOS response objects
spring:
  jackson:
    serialization:
      indent-output: true
