# SERVICE DISCOVERY
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka

# CENTRALIZED CONFIGURATION
# Enable Actuator Refresh Endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://mysql-database:3306/oowg?useSSL=false&allowPublicKeyRetrieval=true
    username: dbuser
    password: dbp4ss
    platform: mysql
  # REST CONTROLLERS
  # Pretty-print JSON for non-HATEOS response objects
  jackson:
    serialization:
      indent-output: true
